---
keys:
  - &personal age14k7pn24n6xn3kpg3n6w49ur4x9g4x0x4zt7yq6pw3gscqqph99csyf8xz9
  - &gamer age1ft9eyy3awfyk5qw9q9gra0ucmp5fpd5uyz9espaxn9e9xnkgh44qezytj8

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *personal
          - *gamer
