---
keys:
  - &master age14k7pn24n6xn3kpg3n6w49ur4x9g4x0x4zt7yq6pw3gscqqph99csyf8xz9
  - &user_stianrs age1rhtsfe9lw4k5ccfzp354f3q0747un9a070swltl6997s8s0yvu0qes0v5w
  - &host_gamer age1ft9eyy3awfyk5qw9q9gra0ucmp5fpd5uyz9espaxn9e9xnkgh44qezytj8
  - &host_laptop age16h52efplmph26cxvucmawlqly8gzwu5c4z2xs2ukv7a9e5zem3qs6hapjc

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *master
          - *user_stianrs
          - *host_gamer
          - *host_laptop
