---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  sop: .taskfiles/sops

tasks:
  default:
    cmd: task --list
    silent: true
