[wagoapp]
src.webpage = "https://addons.wago.io/wagoapp/download?type=linux"
src.regex = 'WagoApp_([0-9.]+)\.AppImage'
fetch.url = "https://cdn.wago.io/wagoapp/WagoApp_$ver.AppImage"
url.name = "WagoApp_$ver.AppImage"

["flate.x86_64-linux"]
fetch.url = "https://github.com/home-operations/flate/releases/download/v$ver/flate_$ver_linux_amd64.tar.gz"
src.github_tag = "home-operations/flate"
src.prefix = "v"

["flate.aarch64-linux"]
fetch.url = "https://github.com/home-operations/flate/releases/download/v$ver/flate_$ver_linux_arm64.tar.gz"
src.github_tag = "home-operations/flate"
src.prefix = "v"

["flate.x86_64-darwin"]
fetch.url = "https://github.com/home-operations/flate/releases/download/v$ver/flate_$ver_darwin_amd64.tar.gz"
src.github_tag = "home-operations/flate"
src.prefix = "v"

["flate.aarch64-darwin"]
fetch.url = "https://github.com/home-operations/flate/releases/download/v$ver/flate_$ver_darwin_arm64.tar.gz"
src.github_tag = "home-operations/flate"
src.prefix = "v"
