# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  flate = {
    pname = "flate";
    version = "0.4.10";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.4.10/flate_0.4.10_linux_amd64.tar.gz";
      sha256 = "sha256-929nlJ7VVjdlj69UwX3QS6vvs8wufK0d3WxNLFj6EHs=";
    };
  };
  kubectl-kopiur = {
    pname = "kubectl-kopiur";
    version = "0.7.3";
    src = fetchurl {
      url = "https://github.com/home-operations/kopiur/releases/download/0.7.3/kubectl-kopiur_0.7.3_linux_amd64.tar.gz";
      sha256 = "sha256-/tI1MRwHYUMq2fttvl30tmJ6DNZWLIm/vgzp8yJGLRY=";
    };
  };
  wagoapp = {
    pname = "wagoapp";
    version = "2.12.1";
    src = fetchurl {
      url = "https://cdn.wago.io/wagoapp/WagoApp_2.12.1.AppImage";
      name = "WagoApp_2.12.1.AppImage";
      sha256 = "sha256-HaufkTAF2eDPBJCuLUwJGAmEZi87YSMqjlge02ULl/g=";
    };
  };
}
