# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  chatgpt-desktop-app = {
    pname = "chatgpt-desktop-app";
    version = "26.803.81509";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/linux/deb/pool/main/c/chatgpt/chatgpt_26.803.81509_amd64.deb";
      sha256 = "sha256-qb+Ro2j598Tuo4CCqfuPtGuNAFtxmm13FdLloZgsOOs=";
    };
  };
  flate = {
    pname = "flate";
    version = "0.5.0";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.5.0/flate_0.5.0_linux_amd64.tar.gz";
      sha256 = "sha256-HdW36NLPloOG33khq8dDhPBNG1srldvum9VGMr1sMRw=";
    };
  };
  kubectl-kopiur = {
    pname = "kubectl-kopiur";
    version = "0.10.2";
    src = fetchurl {
      url = "https://github.com/home-operations/kopiur/releases/download/0.10.2/kubectl-kopiur_0.10.2_linux_amd64.tar.gz";
      sha256 = "sha256-7lEQ/1RnrV5xKeAQkKYFTLvL6VtBlEadCOpGtcy+Xxo=";
    };
  };
  wagoapp = {
    pname = "wagoapp";
    version = "2.14.1";
    src = fetchurl {
      url = "https://cdn.wago.io/wagoapp/WagoApp_2.14.1.AppImage";
      name = "WagoApp_2.14.1.AppImage";
      sha256 = "sha256-QUXUwFrV3Ysv3QZJJ8QUvP8RRaiR62zw3S0sXRGtGG4=";
    };
  };
}
