# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gh-copilot-darwin-amd64 = {
    pname = "gh-copilot-darwin-amd64";
    version = "1.0.5";
    src = fetchurl {
      url = "https://github.com/github/gh-copilot/releases/download/v1.0.5/darwin-amd64";
      sha256 = "sha256-YFQh4vDtT+mjAIMt0IEtleOFTlxkHMbJq/SrI+IzNjc=";
    };
  };
  gh-copilot-darwin-arm64 = {
    pname = "gh-copilot-darwin-arm64";
    version = "1.0.5";
    src = fetchurl {
      url = "https://github.com/github/gh-copilot/releases/download/v1.0.5/darwin-arm64";
      sha256 = "sha256-qVsItCI3LxPraOLtEvVaoTzhoGEcIySTWooMBSMLvAc=";
    };
  };
  gh-copilot-linux-amd64 = {
    pname = "gh-copilot-linux-amd64";
    version = "1.0.5";
    src = fetchurl {
      url = "https://github.com/github/gh-copilot/releases/download/v1.0.5/linux-amd64";
      sha256 = "sha256-QKrDFCVCWYYX2jM8le2X/OLhNcwxR+liUtXHhW7jcSw=";
    };
  };
  gh-copilot-linux-arm64 = {
    pname = "gh-copilot-linux-arm64";
    version = "1.0.5";
    src = fetchurl {
      url = "https://github.com/github/gh-copilot/releases/download/v1.0.5/linux-arm64";
      sha256 = "sha256-+l1hBwep/YMP7EOrEIn2xCIiVgWB0JCWz+fj2ZfivNQ=";
    };
  };
  gh-tidy = {
    pname = "gh-tidy";
    version = "99d0dd50c2b6eb6615ae0f4b6064cfeb14b451da";
    src = fetchFromGitHub {
      owner = "HaywardMorihara";
      repo = "gh-tidy";
      rev = "99d0dd50c2b6eb6615ae0f4b6064cfeb14b451da";
      fetchSubmodules = false;
      sha256 = "sha256-TKQlLnOAozaDkqC7tNlR7KMSqk17sjCe/RTpATBbZlk=";
    };
    date = "2024-02-16";
  };
  kubecolor = {
    pname = "kubecolor";
    version = "v0.0.25";
    src = fetchFromGitHub {
      owner = "hidetatz";
      repo = "kubecolor";
      rev = "v0.0.25";
      fetchSubmodules = false;
      sha256 = "sha256-FyKTI7Br9BjSpmf9ch2E4EZAWM7/jowZfRrCn4GTcps=";
    };
  };
  kubectl-rook-ceph = {
    pname = "kubectl-rook-ceph";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "rook";
      repo = "kubectl-rook-ceph";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-uXHf1TYC0+nwMj4/E/nG1RRlWikA4KptSDi/PoBaSt8=";
    };
  };
  shcopy = {
    pname = "shcopy";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "shcopy";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-2eOzrtWTPLoTR0Bz518SNPKxasRs9QPDP1LAo/kGnMA=";
    };
  };
}
