# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "flate.aarch64-darwin" = {
    pname = "flate.aarch64-darwin";
    version = "0.4.9";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.4.9/flate_0.4.9_darwin_arm64.tar.gz";
      sha256 = "sha256-aCtDtLsuSBi0yfLrLfX13nmnw0Gax1UQubFCsOvNGco=";
    };
  };
  "flate.aarch64-linux" = {
    pname = "flate.aarch64-linux";
    version = "0.4.9";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.4.9/flate_0.4.9_linux_arm64.tar.gz";
      sha256 = "sha256-/q7V23TU4OX0rGMxhLTP4xBRA84nxm7wY0RkOf5jH8A=";
    };
  };
  "flate.x86_64-darwin" = {
    pname = "flate.x86_64-darwin";
    version = "0.4.9";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.4.9/flate_0.4.9_darwin_amd64.tar.gz";
      sha256 = "sha256-TJxboo4+Li3+KLeC3VM4nkVSAqqJ4gt+69u8rZRxVYc=";
    };
  };
  "flate.x86_64-linux" = {
    pname = "flate.x86_64-linux";
    version = "0.4.9";
    src = fetchurl {
      url = "https://github.com/home-operations/flate/releases/download/v0.4.9/flate_0.4.9_linux_amd64.tar.gz";
      sha256 = "sha256-QbjdzihxOfj31cSerWXj2Q7lgArfDi4Q5BCT8cwBjso=";
    };
  };
  wagoapp = {
    pname = "wagoapp";
    version = "2.12.1";
    src = fetchurl {
      url = "https://cdn.wago.io/wagoapp/WagoApp_2.12.1.AppImage";
      name = "WagoApp_2.12.1.AppImage";
      sha256 = "sha256-HaufkTAF2eDPBJCuLUwJGAmEZi87YSMqjlge02ULl/g=";
    };
  };
}
