name: Lint workflows
on:
  pull_request:
    paths:
      - .github/workflows/**
      - .renovaterc.json5
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .renovaterc.json5
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - run: nix shell --inputs-from . nixpkgs#actionlint --command actionlint .github/workflows/*.yaml
