name: Lint workflows
on:
  pull_request:
    paths:
      - .github/workflows/**
      - .renovaterc.json5
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .renovaterc.json5
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Lint workflows
        run: nix shell --inputs-from . nixpkgs#actionlint --command actionlint .github/workflows/*.yaml
      - name: Validate Renovate configuration
        run: nix shell --inputs-from . nixpkgs#renovate --command renovate-config-validator --strict --no-global .renovaterc.json5
