---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Nix Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@bafaa638b9d5ec0e7e3ac1a7fc80453ef1fd265f # v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@135843d9309301ab5a669e972b10b3c9f57a5da4 # main

      - name: Run Nixfmt
        run: 'nix run nixpkgs#nixfmt-tree -- --ci --excludes "**/generated.nix","**/hardware-configuration.nix"'

      - name: Run Statix
        run: 'nix run nixpkgs#statix check'

      - name: Run Deadnix
        run: 'nix run nixpkgs#deadnix -- --exclude ./pkgs/_sources/generated.nix ./hosts/**/hardware-configuration.nix'

      - name: Show changes
        run: git diff