---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Nix Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@bafaa638b9d5ec0e7e3ac1a7fc80453ef1fd265f # v3.20.0

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@ba1df9ab06e525ea302f2a56f5e182f33cfd14fa # main

      - name: Run Nixfmt
        run: 'nix run nixpkgs#nixfmt-tree -- --ci --excludes "**/generated.nix","**/hardware-configuration.nix"'

      - name: Run Statix
        continue-on-error: true
        run: 'nix run nixpkgs#statix check'

      - name: Run Deadnix
        continue-on-error: true
        run: 'nix run nixpkgs#deadnix -- --exclude ./pkgs/_sources/generated.nix ./hosts/**/hardware-configuration.nix'

      - name: Show changes
        run: git diff