---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Nix Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Run Nixfmt
        run: 'nix run nixpkgs#nixfmt-tree -- --ci --excludes "**/generated.nix","**/hardware-configuration.nix"'

      - name: Run Statix
        run: 'nix run nixpkgs#statix -- fix'

      - name: Run Deadnix
        run: 'nix run nixpkgs#deadnix -- --exclude **/generated.nix **/hardware-configuration.nix ./overlays/default.nix'

      - name: Show changes
        run: git diff